app:
  name: Kiwoom SQLite Auto Trader
  run_version: v8

mode: paper

target_codes:
  - "005930"

strategy:
  name: MovingAverageStrategy
  short_window: 5
  long_window: 20

test_order:
  code: "005930"
  qty: 1
  price: 0
  hoga_gb: "03"

order:
  enable_order: false
  allow_live_order: false
  max_buy_amount_per_stock: 300000
  max_holding_count: 3
  max_daily_loss: -30000
  block_if_already_holding: true
  block_if_unfilled_order_exists: true

condition:
  condition_index:
  condition_name:
  screen_no: "4000"

  # HTS 조건검색 반복 실행 안정성을 위해 기본은 일반 조건검색
  # 0: 일반 조건검색
  # 1: 실시간 조건검색
  search_type: 0

  # 일반 조건검색에서는 길게 기다릴 필요가 적음
  watch_seconds: 1

  max_initial_codes: 5
  enable_condition_order: false
  order_max_candidates: 1
  order_qty: 1
  use_initial_codes_for_order: true
  use_realtime_in_for_order: true

sell:
  enable_sell_order: false
  take_profit_rate: 3.0
  stop_loss_rate: -2.0
  only_market_order: true
  max_candidates: 3

trading_loop:
  enable: true
  loop_interval_seconds: 60
  market_open_time: "09:00"
  market_close_time: "15:30"
  allow_loop_outside_market: true
  max_loop_count: 3

  enable_account_sync: true
  enable_sell_check: true
  enable_condition_buy: true

  # v8.1 최적화
  run_condition_each_loop: false
  skip_already_evaluated_condition_codes: true

  # v8.2
  # kiwoon: 키움 HTS 조건검색
  # code : 코드/YAML 기반 조건검색
  # both : 둘 다 실행
  condition_source: code

notification:
  console: true

  # 기본값은 외부 알림 OFF
  # 개인 환경에 따라 settings.local.yaml에서 켜기
  email: false
  telegram: false

  notify_on_info: true
  notify_on_order: true
  notify_on_error: true
  notify_on_loop_summary: true

code_condition:
  enable: true

  # 기본값은 10개 정도가 안전
  # 더 늘리고 싶으면 settings.local.yaml에서 override
  max_universe_size: 10
  max_candidates: 3

  universe:
    type: manual
    codes:
      - "005930"
      - "000660"
      - "035420"
      - "035720"
      - "005380"
      - "000270"
      - "068270"
      - "051910"
      - "005490"
      - "105560"

  filters:
    min_price: 1000
    max_price: 500000
    min_volume: 100000
    exclude_holding: true
    exclude_unfilled: true

  # 키움 TR 과부하 방지
  request_delay_seconds: 1.2
  max_retry: 2

  order:
    enable_order: false
    qty: 1
    max_candidates: 1